// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  adminSecret: __t.string(),
  firstName: __t.string(),
  lastName: __t.string(),
  inviteCode: __t.string(),
  qrToken: __t.option(__t.string()),
  canAddCompanions: __t.bool(),
  maxCompanions: __t.u64(),
  contactEmail: __t.option(__t.string()),
  contactPhone: __t.option(__t.string()),
};
