// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  guestId: __t.u64(),
  rsvpStatus: __t.string(),
  dietaryNotes: __t.option(__t.string()),
  notes: __t.option(__t.string()),
  contactEmail: __t.option(__t.string()),
  contactPhone: __t.option(__t.string()),
  canAddCompanions: __t.bool(),
  maxCompanions: __t.u64(),
};
