// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  AdminGuestPage,
} from "./types";

export const params = {
  adminSecret: __t.string(),
  page: __t.i32(),
  pageSize: __t.i32(),
  search: __t.option(__t.string()),
  rsvpStatus: __t.option(__t.string()),
  hasDietary: __t.option(__t.string()),
  hasCompanions: __t.option(__t.string()),
  messageStatus: __t.option(__t.string()),
};
export const returnType = AdminGuestPage;
