// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdminDashboardSnapshot = __t.object("AdminDashboardSnapshot", {
  get guests() {
    return __t.array(Guest);
  },
  get responses() {
    return __t.array(RsvpResponse);
  },
  get companions() {
    return __t.array(Companion);
  },
  get messages() {
    return __t.array(GuestMessage);
  },
});
export type AdminDashboardSnapshot = __Infer<typeof AdminDashboardSnapshot>;

export const AdminDashboardStats = __t.object("AdminDashboardStats", {
  invited: __t.i32(),
  attending: __t.i32(),
  declining: __t.i32(),
  pending: __t.i32(),
  headcount: __t.i32(),
  dietaryCount: __t.i32(),
  companionCount: __t.i32(),
});
export type AdminDashboardStats = __Infer<typeof AdminDashboardStats>;

export const AdminGuestPage = __t.object("AdminGuestPage", {
  totalGuests: __t.i32(),
  filteredGuests: __t.i32(),
  totalPages: __t.i32(),
  page: __t.i32(),
  pageSize: __t.i32(),
  get stats() {
    return AdminDashboardStats;
  },
  get guests() {
    return __t.array(Guest);
  },
  get responses() {
    return __t.array(RsvpResponse);
  },
  get companions() {
    return __t.array(Companion);
  },
  get messages() {
    return __t.array(GuestMessage);
  },
});
export type AdminGuestPage = __Infer<typeof AdminGuestPage>;

export const AdminInviteCodes = __t.object("AdminInviteCodes", {
  inviteCodes: __t.array(__t.string()),
});
export type AdminInviteCodes = __Infer<typeof AdminInviteCodes>;

export const AdminMessageStats = __t.object("AdminMessageStats", {
  total: __t.i32(),
  newCount: __t.i32(),
  inProgressCount: __t.i32(),
  resolvedCount: __t.i32(),
});
export type AdminMessageStats = __Infer<typeof AdminMessageStats>;

export const AdminMessagePage = __t.object("AdminMessagePage", {
  totalMessages: __t.i32(),
  totalPages: __t.i32(),
  page: __t.i32(),
  pageSize: __t.i32(),
  get messageStats() {
    return AdminMessageStats;
  },
  get guests() {
    return __t.array(Guest);
  },
  get messages() {
    return __t.array(GuestMessage);
  },
});
export type AdminMessagePage = __Infer<typeof AdminMessagePage>;

export const AdminIdentity = __t.object("AdminIdentity", {
  id: __t.u64(),
  identity: __t.identity(),
  claimedAt: __t.timestamp(),
});
export type AdminIdentity = __Infer<typeof AdminIdentity>;

export const Companion = __t.object("Companion", {
  id: __t.u64(),
  guestId: __t.u64(),
  name: __t.string(),
  dietaryNotes: __t.option(__t.string()),
  relationship: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type Companion = __Infer<typeof Companion>;

export const CompanionInput = __t.object("CompanionInput", {
  name: __t.string(),
  dietaryNotes: __t.option(__t.string()),
  relationship: __t.option(__t.string()),
});
export type CompanionInput = __Infer<typeof CompanionInput>;

export const Guest = __t.object("Guest", {
  id: __t.u64(),
  firstName: __t.string(),
  lastName: __t.string(),
  inviteCode: __t.string(),
  contactEmail: __t.option(__t.string()),
  contactPhone: __t.option(__t.string()),
  rsvpStatus: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Guest = __Infer<typeof Guest>;

export const GuestMessage = __t.object("GuestMessage", {
  id: __t.u64(),
  guestId: __t.u64(),
  message: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type GuestMessage = __Infer<typeof GuestMessage>;

export const GuestPortalState = __t.object("GuestPortalState", {
  get previewGuest() {
    return __t.option(GuestPreview);
  },
  get activeGuest() {
    return __t.option(Guest);
  },
  get activeRsvp() {
    return __t.option(RsvpResponse);
  },
  get companions() {
    return __t.array(Companion);
  },
  get messages() {
    return __t.array(GuestMessage);
  },
});
export type GuestPortalState = __Infer<typeof GuestPortalState>;

export const GuestPreview = __t.object("GuestPreview", {
  firstName: __t.string(),
  lastName: __t.string(),
  inviteCode: __t.string(),
});
export type GuestPreview = __Infer<typeof GuestPreview>;

export const GuestSession = __t.object("GuestSession", {
  sender: __t.identity(),
  guestId: __t.u64(),
  verifiedAt: __t.timestamp(),
});
export type GuestSession = __Infer<typeof GuestSession>;

export const RsvpResponse = __t.object("RsvpResponse", {
  id: __t.u64(),
  guestId: __t.u64(),
  attendance: __t.bool(),
  dietaryNotes: __t.option(__t.string()),
  notes: __t.option(__t.string()),
  submitted: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type RsvpResponse = __Infer<typeof RsvpResponse>;
