// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdminDashboardSnapshot = __t.object("AdminDashboardSnapshot", {
  get guests() {
    return __t.array(Guest);
  },
  get responses() {
    return __t.array(RsvpResponse);
  },
  get companions() {
    return __t.array(Companion);
  },
  get messages() {
    return __t.array(GuestMessage);
  },
});
export type AdminDashboardSnapshot = __Infer<typeof AdminDashboardSnapshot>;

export const AdminIdentity = __t.object("AdminIdentity", {
  id: __t.u64(),
  identity: __t.identity(),
  claimedAt: __t.timestamp(),
});
export type AdminIdentity = __Infer<typeof AdminIdentity>;

export const Companion = __t.object("Companion", {
  id: __t.u64(),
  guestId: __t.u64(),
  name: __t.string(),
  dietaryNotes: __t.option(__t.string()),
  relationship: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type Companion = __Infer<typeof Companion>;

export const CompanionInput = __t.object("CompanionInput", {
  name: __t.string(),
  dietaryNotes: __t.option(__t.string()),
  relationship: __t.option(__t.string()),
});
export type CompanionInput = __Infer<typeof CompanionInput>;

export const Guest = __t.object("Guest", {
  id: __t.u64(),
  firstName: __t.string(),
  lastName: __t.string(),
  inviteCode: __t.string(),
  qrToken: __t.string(),
  contactEmail: __t.option(__t.string()),
  contactPhone: __t.option(__t.string()),
  rsvpStatus: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Guest = __Infer<typeof Guest>;

export const GuestMessage = __t.object("GuestMessage", {
  id: __t.u64(),
  guestId: __t.u64(),
  message: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type GuestMessage = __Infer<typeof GuestMessage>;

export const GuestPortalState = __t.object("GuestPortalState", {
  get previewGuest() {
    return __t.option(GuestPreview);
  },
  get activeGuest() {
    return __t.option(Guest);
  },
  get activeRsvp() {
    return __t.option(RsvpResponse);
  },
  get companions() {
    return __t.array(Companion);
  },
  get messages() {
    return __t.array(GuestMessage);
  },
});
export type GuestPortalState = __Infer<typeof GuestPortalState>;

export const GuestPreview = __t.object("GuestPreview", {
  firstName: __t.string(),
  lastName: __t.string(),
  inviteCode: __t.string(),
});
export type GuestPreview = __Infer<typeof GuestPreview>;

export const GuestSession = __t.object("GuestSession", {
  sender: __t.identity(),
  guestId: __t.u64(),
  verifiedAt: __t.timestamp(),
});
export type GuestSession = __Infer<typeof GuestSession>;

export const RsvpResponse = __t.object("RsvpResponse", {
  id: __t.u64(),
  guestId: __t.u64(),
  attendance: __t.bool(),
  dietaryNotes: __t.option(__t.string()),
  notes: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type RsvpResponse = __Infer<typeof RsvpResponse>;

